In [5]:
from keras.models import Sequential
from keras.layers import *
import numpy as np

def start(neuron1, neuron2):
    m = Sequential() 
    m.add(Dense(neuron1,input_dim=2, activation='tanh'))
    m.add(Dense(neuron2,input_dim=2, activation='tanh'))
    m.add(Dense(1,activation='sigmoid'))

    X = np.array([[0,0],[0,1],[1,0],[1,1]],'float32')
    Y = np.array([[0],[1],[1],[0]],'float32')
    m.compile(optimizer='adam',loss='binary_crossentropy')

    m.fit(X,Y,batch_size=1,epochs=200,verbose=0)
    print(m.predict(X))

    print('OR')
    X1 = np.array([[0,0],[0,1],[1,0],[1,1]],'float32')
    Y1 = np.array([[0],[1],[1],[1]],'float32')

    m.fit(X1,Y1,batch_size=1,epochs=200,verbose=0)
    print(m.predict(X1))

    X2 = np.array([[0,0],[0,1],[1,0],[1,1]],'float32')
    Y2 = np.array([[1],[0],[0],[0]],'float32')

    print('NOR')
    m.fit(X2,Y2,batch_size=1,epochs=200,verbose=0)
    print(m.predict(X2))

    X3 = np.array([[0,0],[0,1],[1,0],[1,1]],'float32')
    Y3 = np.array([[0],[0],[0],[1]],'float32')

    print('AND')
    m.fit(X3,Y3,batch_size=1,epochs=200,verbose=0)
    print(m.predict(X3))

    X4 = np.array([[0,0],[0,1],[1,0],[1,1]],'float32')
    Y4 = np.array([[1],[1],[1],[0]],'float32')

    print('NAND')
    m.fit(X4,Y4,batch_size=1,epochs=200,verbose=0)
    print(m.predict(X4))

In [8]:
print("Architecture 1")
start(6,9)

Architecture 1
1/1 [==============================] - 0s 43ms/step
[[0.3766737 ]
 [0.5401601 ]
 [0.46496212]
 [0.49634472]]
OR
1/1 [==============================] - 0s 15ms/step
[[0.16787887]
 [0.942744  ]
 [0.9206551 ]
 [0.9876577 ]]
NOR
1/1 [==============================] - 0s 15ms/step
[[0.50465596]
 [0.10343917]
 [0.16812946]
 [0.04414391]]
AND
1/1 [==============================] - 0s 15ms/step
[[0.11629706]
 [0.21446425]
 [0.32670376]
 [0.4929117 ]]
NAND
1/1 [==============================] - 0s 15ms/step
[[0.7664462]
 [0.7037525]
 [0.7267554]
 [0.6043175]]


In [9]:
print("Architecture 2")
start(3,8)

Architecture 2
1/1 [==============================] - 0s 43ms/step
[[0.48757228]
 [0.46992856]
 [0.5201679 ]
 [0.48050293]]
OR
1/1 [==============================] - 0s 15ms/step
[[0.18908161]
 [0.91841245]
 [0.9403618 ]
 [0.9692724 ]]
NOR
1/1 [==============================] - 0s 17ms/step
[[0.5626125 ]
 [0.14388947]
 [0.18806165]
 [0.08444736]]
AND
1/1 [==============================] - 0s 15ms/step
[[0.17628941]
 [0.2402638 ]
 [0.36443377]
 [0.3937443 ]]
NAND
1/1 [==============================] - 0s 14ms/step
[[0.6822278 ]
 [0.6820456 ]
 [0.71469396]
 [0.7005295 ]]
